import Head from 'next/head'
import Image from 'next/image'
import Button from 'antd/lib/button'
import styles from '../styles/Home.module.css'
import Navigation from './components/navigation'

export default function Home() {
  return (

    <div className={styles.container}>
      <Navigation />
      <Head>
        <title>Open Brewery App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/search">Next.js!</a>
          <Button></Button>
        </h1>
      </main>
    </div>

  )
}
