import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Navigation } from './components/navigation'

export default function Search() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Open Brewery App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Fart Mouth
                </h1>
            </main>
        </div>
    )
}
